Repository clouddrove/terraform-azure-virtual-machine, pull requests merged in 2023-05, with the labels that each got.

#19 [Issues-53] Fix - availibility naming format changed
  main.tf
Labels: bug

#21 Updated type variable of identity resource in windows VM resource
  main.tf
Labels: bug, enhancement

#20 feat: auto changelog action added
  .github/workflows/changelog.yaml
  CHANGELOG.md
Labels: enhancement

#23 feat: added dependabot.yml file
  .github/dependabot.yml
Labels: enhancement

#32 ci: Update changelog
  .github/workflows/changelog.yaml
Labels: bug, enhancement

#40 fix: add default value in variable.tf
  README.yaml
  _example/linux-vm/example.tf
  _example/windows-vm/example.tf
  variables.tf
Labels: enhancement
